In [1]:
import numpy as np

# The Basics

In [ ]:
a = np.array([[1.0,2.0,3.0],
            [4.0,5.0,6.0]])
print(a)

In [ ]:
# Get shape and data type
print(a.shape)
print(a.dtype)

In [ ]:
# changing datatype
np.array([0.0, 1.0], dtype="int8")

In [ ]:
np.zeros((5,2))

In [ ]:
# useful!
p.full((2,2), 99)

Random numbers in an array

In [21]:
np.random.rand(4,2)

array([[0.96053233, 0.55743611],
       [0.67833799, 0.43378659],
       [0.31421543, 0.42450406],
       [0.85011731, 0.28895466]])

In [28]:
np.random.randint(4, 7, size=(7,2))

array([[6, 6],
       [5, 4],
       [5, 6],
       [6, 5],
       [5, 5],
       [5, 4],
       [6, 5]])

Creating a sequence

In [33]:
seq = np.arange(1, 10, 0.5)
seq.shape

(18,)

Reshaping

In [58]:
seq.reshape((3,6))

array([[1. , 1.5, 2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5, 6. , 6.5],
       [7. , 7.5, 8. , 8.5, 9. , 9.5]])

In [62]:
a = np.array([[3., 7., 3., 4.],
            [1., 4., 2., 2.],
            [7., 2., 4., 9.]])

a.reshape(2, -1)  # -1 is like saying "calculate everything else on your own numpy"

array([[3., 7., 3., 4., 1., 4.],
       [2., 2., 7., 2., 4., 9.]])

## Math

In [41]:
A = np.array([[1,2,3],
            [8,7,6],
            [0,2,4]])

B = np.array([[5,2,2],
            [0,2,3],
            [9,7,1]])

In [43]:
# element-wise mult:
A * B 

array([[ 5,  4,  6],
       [ 0, 14, 18],
       [ 0, 14,  4]])

In [42]:
# matrix product 
A @ B

array([[32, 27, 11],
       [94, 72, 43],
       [36, 32, 10]])

In [45]:
# dot - same as matrix mult here
A.dot(B)

array([[32, 27, 11],
       [94, 72, 43],
       [36, 32, 10]])

In [50]:
x = np.linspace(0, 6.28, 100)  # useful to evaluate functions with many inputs
f = np.sin(x)

#### Concept of axis

In [51]:
a = np.array([[1,2,4,5],
            [0,2,3,7]])

In [52]:
a.sum(axis=0) # down the columns

array([ 1,  4,  7, 12])

In [53]:
a.min(axis=1) # along each row 

array([1, 0])

In [57]:
for elem in a.flat:
    print(elem)

1
2
4
5
0
2
3
7
